"""Regenerate the deterministic v5 SQL fixture; protobuf bytes match JSON facts."""
import hashlib
import json
from pathlib import Path

DATASET = "11111111-1111-4111-8111-111111111111"
RUN = "22222222-2222-4222-8222-222222222222"
PARENT = bytes.fromhex("ab" * 32)
HEIGHT = 970144
STAMP = 1790200000000
CAPS = ["event_facts", "event_observations", "tip_observations", "snapshot_consistency", "extractor_status", "per_worker_health", "resumable_sidechain_history", "resumable_global_bip300_history", "raw_bip300_coinbase_scripts", "resolved_m1_m8_deltas", "treasury_transitions", "live_bmm_bid_snapshots", "mempool_backed_bmm_bid_snapshots"]

def varint(value):
    out = bytearray()
    while value > 127:
        out.append((value & 127) | 128)
        value >>= 7
    out.append(value)
    return bytes(out)

def field(number, value):
    if isinstance(value, int):
        return varint(number << 3) + varint(value)
    return varint((number << 3) | 2) + varint(len(value)) + value

def literal(value):
    return "'" + value.replace("'", "''") + "'"

def bytea(value):
    return "decode('" + value.hex() + "','hex')"

def fact(id, kind, variant, tag, payload, wire, slot=None, version=5):
    body = field(tag, wire)
    observed = field(1, PARENT) + field(2, HEIGHT)
    envelope = field(1, body) + field(10, STAMP) + field(11, observed)
    document = {"timestamp": STAMP, "observed_at_block": {"hash": PARENT.hex(), "height": HEIGHT}, "monitor_event": {"Enforcer": {"event": {variant: payload}}}}
    values = [str(id), "to_timestamp(%d / 1000.0)" % STAMP, "'enforcer'", literal(kind), str(slot) if slot is not None else "NULL", bytea(PARENT), str(HEIGHT), bytea(envelope), literal(json.dumps(document)), literal(DATASET), str(version), bytea(hashlib.sha256(envelope).digest()), bytea(hashlib.sha256(body).digest()), "'betanet-slot-9-fixture'" if slot == 9 else "NULL"]
    return "INSERT INTO event (id,observed_at,source,kind,sidechain,block_hash,height,envelope,payload,dataset_id,event_contract_version,envelope_sha256,fact_sha256,sidechain_instance_id) OVERRIDING SYSTEM VALUE VALUES (" + ",".join(values) + ");\n"

header = {"hash": PARENT.hex(), "previous_hash": "aa" * 32, "height": HEIGHT, "chain_work": "01" + "00" * 31, "timestamp": STAMP // 1000}
header_wire = field(1, PARENT) + field(2, bytes.fromhex("aa" * 32)) + field(3, HEIGHT) + field(4, bytes.fromhex(header["chain_work"])) + field(5, STAMP // 1000)
bid = {"sidechain_number": 9, "txid": "12" * 32, "critical_hash": "34" * 32, "bid_sats": 18446744073709551615}
bid_wire = field(1, 9) + field(2, bytes.fromhex(bid["txid"])) + field(3, bytes.fromhex(bid["critical_hash"])) + field(4, bid["bid_sats"])
text = f"""-- Generated by fixtures/generate.py. Envelopes are actual protobuf wire bytes.
INSERT INTO dataset_manifest (dataset_id,network_id,activation_height,activation_block_hash,initial_node_commit,initial_enforcer_commit,initial_monitor_commit,initial_event_contract_version,capabilities,creation_reason)
VALUES ('{DATASET}','betanet',967680,'00000000000000030101ba5cfea54b22becc79f95dc6040beb76e01dd9d04042','ca64033c137457a3c8ca394186759819a2ab0694','0740a39380b39885fe8655f79f78150001d8a15b','490cdfa6cb87',4,'[]','Pulse v4 to v5 integration fixture');
INSERT INTO extractor_run (run_id,dataset_id,source,node_commit,enforcer_commit,monitor_commit,event_contract_version,capabilities,status,last_capture_seq)
VALUES ('{RUN}','{DATASET}','enforcer','ca64033c137457a3c8ca394186759819a2ab0694','0740a39380b39885fe8655f79f78150001d8a15b','86e83787b7c1dd32e404ded6ef26404f63f49359',5,'{json.dumps(CAPS)}','running',6);
INSERT INTO sidechain_instance (dataset_id,sidechain_instance_id,sidechain,raw_description,description_sha256d,proposal_height,activation_height)
VALUES ('{DATASET}','betanet-slot-9-fixture',9,decode('01020304','hex'),decode(repeat('99',32),'hex'),967989,968998);
INSERT INTO current_sidechain_instance (dataset_id,sidechain,sidechain_instance_id,observed_at)
VALUES ('{DATASET}',9,'betanet-slot-9-fixture',now());
"""
text += fact(1, "bip300_block_delta", "Bip300BlockDelta", 10, {"header": header, "coinbase_txid": "56" * 32, "coinbase_messages": [], "treasury_transitions": [], "confirmed_bmm_requests": []}, field(1, header_wire) + field(2, bytes.fromhex("56" * 32)))
text += fact(2, "block_connected", "BlockConnected", 6, {"header": header, "sidechain_number": 9, "bmm_commitment": None, "events": []}, field(1, header_wire) + field(2, 9), slot=9)
text += fact(3, "bmm_requests", "BmmRequests", 11, {"previous_mainchain_block_hash": PARENT.hex(), "requests": [bid]}, field(1, PARENT) + field(2, bid_wire))
text += fact(4, "bmm_requests", "BmmRequests", 11, {"previous_mainchain_block_hash": PARENT.hex(), "requests": []}, field(1, PARENT))
text += fact(5, "chain_info", "ChainInfo", 1, {"network": 2, "bip300_constants": None, "raw_network": 2}, field(1, 2) + field(3, 2), version=4)
# A blocked occurrence (2 -> fact 3) precedes a replay of an already imported fact.
for obs, event in [(1, 1), (2, 3), (3, 2), (4, 4), (5, 3)]:
    text += f"INSERT INTO event_observation (observation_id,dataset_id,run_id,capture_seq,capture_method,event_id,observed_at) OVERRIDING SYSTEM VALUE VALUES ({obs},'{DATASET}','{RUN}',{obs},'poll',{event},now());\n"
text += f"""INSERT INTO tip_observation (tip_observation_id,dataset_id,run_id,capture_seq,capture_method,tip_hash,tip_height,observed_at)
OVERRIDING SYSTEM VALUE VALUES (1,'{DATASET}','{RUN}',6,'poll',decode(repeat('ab',32),'hex'),970144,now());
INSERT INTO extractor_status (dataset_id,source,run_id,last_tip_hash,last_tip_height)
VALUES ('{DATASET}','enforcer','{RUN}',decode(repeat('ab',32),'hex'),970144);
INSERT INTO extractor_worker_status (run_id,worker,last_success_at)
VALUES ('{RUN}','mainchain_tip',now()),('{RUN}','bmm_requests',now());
INSERT INTO history_coverage (dataset_id,event_contract_version,source,stream,coverage_start_height,covered_tip_hash,covered_tip_height,target_tip_hash,target_tip_height,status,effective_page_blocks,completed_at)
VALUES ('{DATASET}',5,'enforcer','bip300_delta',967680,decode(repeat('ab',32),'hex'),970144,decode(repeat('ab',32),'hex'),970144,'complete',128,now());
SELECT setval(pg_get_serial_sequence('event','id'),5,true);
SELECT setval(pg_get_serial_sequence('event_observation','observation_id'),5,true);
SELECT setval(pg_get_serial_sequence('tip_observation','tip_observation_id'),1,true);
"""
Path(__file__).with_name("0005_source_fixture.sql").write_text(text)
