import Link from "next/link";
export default function Page() {
  return <main className="detail-shell"><div className="eyebrow">READ THE PROTOCOL</div><h1>Learn Drivechain</h1><p className="lede">Read each mechanism alongside real observations. Observatory describes the monitor’s view of eCash Betanet; the selected branch is limited by imported evidence.</p>
    <section className="panel compact-panel"><h2>From proposal to active instance</h2><ol className="protocol-flow"><li><strong>M1 · Propose</strong><p>A declaration identifies a candidate for a numbered slot. A new proposal begins with zero votes.</p></li><li><strong>M2 · Acknowledge</strong><p>Accepted acknowledgements vote for a proposal from an earlier block. Activation requires strictly more votes than the applicable threshold.</p></li><li><strong>Activate or expire</strong><p>Used and unused slots have different rules. A replacement creates a new instance; the slot number alone is not its identity.</p></li></ol><Link className="text-link" href="/proposals">Inspect observed proposals →</Link></section>
    <section className="panel compact-panel"><h2>Treasury, deposits and withdrawals</h2><ol className="protocol-flow"><li><strong>M5 · Deposit</strong><p>A deposit replaces the current treasury output (CTIP). Its value increases by the deposit amount.</p></li><li><strong>M3 / M4 · Submit and vote</strong><p>A new withdrawal attempt starts with one vote. Resolved votes may increase or decrease that count. A repeated bundle identifier can have separate attempts.</p></li><li><strong>M6 · Withdraw</strong><p>An observed successful withdrawal reduces treasury value by payout plus fee. They are shown separately. Observing a deposit on L1 does not establish an L2 credit.</p></li></ol><Link className="text-link" href="/pegs">Inspect deposits and withdrawal attempts →</Link></section>
    <section className="panel compact-panel"><h2>Blind merged mining</h2><div className="explanation-grid"><div><h3>Sampled bid</h3><p>A poll reports the requests visible at that instant. An empty successful poll differs from a failed or inconsistent capture.</p></div><div><h3>M7 commitment</h3><p>A slot’s commitment is observed in an L1 block. Coverage is needed to distinguish an observed absence from a missing observation.</p></div><div><h3>M8 confirmed request</h3><p>A confirmed transaction is separate evidence. Fees can be confirmed only for observed bids that match an official commitment and a transaction with available prevouts. Other fees remain unknown.</p></div></div><Link className="text-link" href="/bmm">Explore BMM evidence and coverage →</Link></section>
    <section className="panel compact-panel"><h2>Reading confidence and history</h2><dl className="facts"><dt>Observed</dt><dd>A decoded source fact or validated snapshot occurrence. Read its branch membership and capture boundary.</dd><dt>Reconstructed</dt><dd>State derived with the pinned enforcer’s rules from a known baseline and sufficient continuous evidence.</dd><dt>Unknown</dt><dd>A missing baseline, gap, invalid payload, conflicting observation or unsupported rule prevents a conclusion.</dd><dt>Alternative branch</dt><dd>Retained evidence outside the currently selected branch. It remains inspectable after a reorganization.</dd><dt>Time</dt><dd>Block time, observation time and ingestion time answer different questions. The explorer lets you choose which one to filter.</dd></dl><Link className="text-link" href="/about/data">Read builds, parameters and coverage →</Link></section>
  </main>;
}
